### ISSUE TITLE
Generování stylů nefunguje ve Windows

### ISSUE THREAD

**Issue by janpipek** [pm13/hrbatypes#1]
Nemá to rádo symlinky.

```
Traceback (most recent call last): 
  File "generate-style.py", line 27, in <module> 
    generate_style()
  File "C:\Miniconda3\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Miniconda3\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Miniconda3\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params) 
  File "C:\Miniconda3\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "generate-style.py", line 19, in generate_style
    bootstrap_link_path.symlink_to(bootstrap_path)
  File "C:\Miniconda3\lib\pathlib.py", line 1330, in symlink_to
    self._accessor.symlink(target, self, target_is_directory)
OSError: symbolic link privilege not held
```

**Comment by pm13** [comment]
Generování stylů je potřeba jen při úpravě vzhledu nebo při upgradu bootstrapu - což se děje jen málo často. A nepřipadá mi tudíž nezbytné, aby to fungovalo i ve Windows. Tudíž bych nechal být.
